version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: moodcube-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: moodcube-pgadmin

    env_file:
      - .env

    ports:
      - "${PGADMIN_PORT}:80"

    depends_on:
      - postgres

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: moodcube-azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"

volumes:
  postgres_data: